- ros_topic_name: "/clock" # we choose this
  gz_topic_name: "/clock" # this is from gz
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS # or ROS_TO_GZ or BIDIRECTIONAL

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/libot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/libot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Wheels
- ros_topic_name: "/back_left_wheel/cmd_vel"
  gz_topic_name: "/model/libot/joint/base_back_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/back_right_wheel/cmd_vel"
  gz_topic_name: "/model/libot/joint/base_back_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/front_left_wheel/cmd_vel"
  gz_topic_name: "/model/libot/joint/base_front_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/front_right_wheel/cmd_vel"
  gz_topic_name: "/model/libot/joint/base_front_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Arm
- ros_topic_name: "/arm_revolute/cmd_vel"
  gz_topic_name: "/model/libot/joint/libot_arm_base_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/arm_vertical/cmd_vel"
  gz_topic_name: "/model/libot/joint/vertical_prismatic1_2_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/arm_horizontal/cmd_vel"
  gz_topic_name: "/model/libot/joint/horizontal_prismatic1_2_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/arm_roll/cmd_vel"
  gz_topic_name: "/model/libot/joint/horizontal_prismatic3_roll_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/arm_pitch/cmd_vel"
  gz_topic_name: "/model/libot/joint/roll_pitch_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Gripper
- ros_topic_name: "/gripper/cmd_pos"
  gz_topic_name: "/model/libot/joint/gripper_left_finger_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ